name: Deploy Laravel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil source code
        uses: actions/checkout@v4

      - name: Cek workflow
        run: echo "Workflow berhasil dijalankan"
